// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWMPMfiye2m-0Lg73Fjmav8NjS12eD6x4',
    appId: '1:316272631183:web:c75395f207a2081ba47ffa',
    messagingSenderId: '316272631183',
    projectId: 'chat-boot-e7b5b',
    authDomain: 'chat-boot-e7b5b.firebaseapp.com',
    storageBucket: 'chat-boot-e7b5b.firebasestorage.app',
    measurementId: 'G-P2YTRLCDG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB29dh4ktaQ40kKp5rDr1e6pznl2EmHklg',
    appId: '1:316272631183:android:e8e82676340d745da47ffa',
    messagingSenderId: '316272631183',
    projectId: 'chat-boot-e7b5b',
    storageBucket: 'chat-boot-e7b5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0eTMPYfJ7XIAUICuO4l326cWQSX9LdXw',
    appId: '1:316272631183:ios:66114050c4b37707a47ffa',
    messagingSenderId: '316272631183',
    projectId: 'chat-boot-e7b5b',
    storageBucket: 'chat-boot-e7b5b.firebasestorage.app',
    iosBundleId: 'com.example.chatBoot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0eTMPYfJ7XIAUICuO4l326cWQSX9LdXw',
    appId: '1:316272631183:ios:66114050c4b37707a47ffa',
    messagingSenderId: '316272631183',
    projectId: 'chat-boot-e7b5b',
    storageBucket: 'chat-boot-e7b5b.firebasestorage.app',
    iosBundleId: 'com.example.chatBoot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWMPMfiye2m-0Lg73Fjmav8NjS12eD6x4',
    appId: '1:316272631183:web:3173cf0a34b56955a47ffa',
    messagingSenderId: '316272631183',
    projectId: 'chat-boot-e7b5b',
    authDomain: 'chat-boot-e7b5b.firebaseapp.com',
    storageBucket: 'chat-boot-e7b5b.firebasestorage.app',
    measurementId: 'G-ZV3LQQJDVT',
  );
}
